@startuml

'abstract class AbstractList
'abstract AbstractCollection
'interface List
'interface Collection
'
'List <|-- AbstractList
'Collection <|-- AbstractCollection
'
'Collection <|- List
'AbstractCollection <|- AbstractList
'AbstractList <|-- ArrayList
'
'class ArrayList {
'Object[] elementData
'size()
'}
'
'enum TimeUnit {
'DAYS
'HOURS
'MINUTES
'}
class GenericRequestBuilder
class BitmapRequestBuilder
class DrawableRequestBuilder
class GifRequestBuilder
class GenericTranscodeRequest
class DrawableTypeRequest


GenericRequestBuilder <|-- BitmapRequestBuilder
GenericRequestBuilder <|-- DrawableRequestBuilder
GenericRequestBuilder <|-- GifRequestBuilder
GenericRequestBuilder <|-- GenericTranscodeRequest
DrawableRequestBuilder <|-- DrawableTypeRequest
BitmapRequestBuilder <|-- BitmapTypeRequest
GifRequestBuilder <|-- GifTypeRequest
@enduml