@startuml

'abstract class AbstractList
'abstract AbstractCollection
'interface List
'interface Collection
'
'List <|-- AbstractList
'Collection <|-- AbstractCollection
'
'Collection <|- List
'AbstractCollection <|- AbstractList
'AbstractList <|-- ArrayList
'
'class ArrayList {
'Object[] elementData
'size()
'}
'
'enum TimeUnit {
'DAYS
'HOURS
'MINUTES
'}
 interface Request {


    void begin();

    void pause();
    void clear();
    boolean isPaused();
    boolean isRunning();
    boolean isComplete();
    boolean isResourceSet();
    boolean isCancelled();
    boolean isFailed();
    void recycle();
}

Request<|--GenericRequest
Request<|--ThumbnailRequestCoordinator
@enduml