@startuml

'abstract class AbstractList
'abstract AbstractCollection
'interface List
'interface Collection
'
'List <|-- AbstractList
'Collection <|-- AbstractCollection
'
'Collection <|- List
'AbstractCollection <|- AbstractList
'AbstractList <|-- ArrayList
'
'class ArrayList {
'Object[] elementData
'size()
'}
'
'enum TimeUnit {
'DAYS
'HOURS
'MINUTES
'}

 interface Resource{
Z get();
int getSize();
void recycle();
}

class EngineResource{

   private final Resource<Z> resource;
    private final boolean isCacheable;
    private ResourceListener listener;
    private Key key;
    private int acquired;
    private boolean isRecycled;
    void release();
    void acquire();
}
  interface ResourceListener {
        void onResourceReleased(Key key, EngineResource<?> resource);
    }

EngineResource..>ResourceListener
 Resource<|--EngineResource
@enduml