@startuml

scale 550 width
scale 750 width
 interface ResourceCallback {
    void onResourceReady(Resource<?> resource);

    void onException(Exception e);
}

interface EngineRunnableManager{
 void submitForSource(EngineRunnable runnable);
}
class EngineJob{
EngineResource engineResource;
void onResourceReady();
void handleResultOnMainThread()
}
note left of EngineJob
 <size:12> EngineRunnable加载成功与否
 <size:12>会通过manager通知自己
end note
ResourceCallback <|-- EngineRunnableManager
EngineRunnableManager <|-- EngineJob

class EngineRunnable{
EngineRunnableManager manager;
void run();
void onLoadFailed();
void onLoadComplete();

}
EngineRunnable *-- EngineRunnableManager
@enduml