@startuml
scale 450 height
'Alice -> Bob: Authentication Request
'Bob --> Alice: Authentication Response
'
'Alice -> Bob: Another authentication Request
'Alice <-- Bob: another authentication Response
Executor ->EngineRunnable:run
EngineRunnable ->EngineRunnable:onLoadComplete
EngineRunnable->EngineJob:onResourceReady
EngineJob->EngineJob:handleResultOnMainThread
EngineJob->EngineResourceFactory:build
note left:engineResource登场\

EngineJob->GenericRequest:onSizeReady
GenericRequest->ImageViewTarget:onResourceReady
ImageViewTarget->BitmapImageViewTarget:setResource
BitmapImageViewTarget->view:setImageBitmap
@enduml