@startuml

 interface Target{

    void onLoadStarted(Drawable placeholder);

    void onLoadFailed(Exception e, Drawable errorDrawable);


    void onResourceReady(R resource, GlideAnimation<? super R> glideAnimation);


    void onLoadCleared(Drawable placeholder);


    void getSize(SizeReadyCallback cb);


    void setRequest(Request request);


    Request getRequest();
}

interface LifecycleListener{
    void onStart();
    void onStop();
    void onDestroy();
}

class BaseTarget{
对接口的一些空实现
}
class ViewTarget{
主要对getSize做了实现
}
LifecycleListener<|--Target
Target<|--BaseTarget
BaseTarget<|--ViewTarget
ViewTarget<|--ImageViewTarget
ImageViewTarget<|--GlideDrawableImageViewTarget
ImageViewTarget<|--BitmapImageViewTarget
ImageViewTarget<|--DrawableImageViewTarget


@enduml