@startuml
'Alice -> Bob: Authentication Request
'Bob --> Alice: Authentication Response
'
'Alice -> Bob: Another authentication Request
'Alice <-- Bob: another authentication Response
Fragment -> RequestManagerFragment:onStart
RequestManagerFragment-> ActivityFragmentLifecycle:onStart
ActivityFragmentLifecycle->RequestManager:onStart


@enduml