@startuml

skinparam titleBorderRoundCorner 15
skinparam titleBorderThickness 2
skinparam titleBorderColor red
skinparam titleBackgroundColor Aqua-CadetBlue
title Resources类图
scale 1.5
interface Resource<<Z>>{
 Z get()
  int getSize()
   void recycle()
 }
Resource <|.. BitmapResource
Resource <|.. BytesResource
Resource <|.. DrawableResource
Resource <|.. SimpleResource

Resource <|.. GifBitmapWrapperResource
Resource <|.. EngineResource

DrawableResource <|--BitmapDrawableResource
DrawableResource <|--GlideBitmapDrawableResource
DrawableResource <|--GifDrawableResource

class EngineResource <<Z>>{
  Resource<Z> resource
     final boolean isCacheable
     ResourceListener listener
     Key key
     int acquired
     boolean isRecycled

     void acquire()
     void release()
}

@enduml